### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by mayconvm** [mayconvm/learning-phalcon-php#1]
- [x] Write script file to environment DEV
    - [x] Make docker-composer
        - [x] Container with php-phalcon
        - [x] Container with Nginx
    - [x] Build Project

- [ ] Mysql
    - [ ] Create tables
        - [ ] Players
        - [ ] Match
        - [ ] Points

- [ ] API
    - [ ] CRUD Players
    - [ ] CRUD Match
    - [ ] CRUD Points

- [ ] Monitoring
    - [ ] Write script file to environment DEV
        - [ ] Container with Beats (https://www.elastic.co/products/beats)
        - [ ] Container with Logstash
        - [ ] Container with ElasticSearch
        - [ ] Container with Kibana
    - [ ] Beats observer Nginx
    - [ ] Beats connect Logstash
        - [ ] Transform log Nginx
    - [ ] Logstash send log to Elastcsearch
    - [ ] Connect Kibana in Elastcsearch
